#!/usr/bin/env python3
"""
setup_library.py — Scaffold a new RAG library and register it with the toolkit.

Creates the standard library layout, writes a LIBRARY.md + CONTEXT.md starter,
patches the _KB_REGISTRY in src/kb_config.py, and optionally emits a
~/.local/bin/<name>-rag wrapper. After running, the new library is immediately
usable (index + query) — no other code edits needed.

Usage:
    # Interactive (prompts for everything, sensible defaults):
    /usr/bin/python3.10 -B scripts/setup_library.py

    # Fully non-interactive:
    /usr/bin/python3.10 -B scripts/setup_library.py \
        --name neuro_rag \
        --root /path/to/RAG_home/neuro_rag \
        --collection neuro_papers \
        --domain "neuroscience / axon guidance" \
        --wrapper

Requires: write access to the RAG home (default: parent of this repo) and the
bib_rag repo. Never touches
existing libraries — refuses if the target root already exists (use --force
to scaffold into an existing directory that lacks the standard subdirs).
"""
import argparse
import os
import re
import sys
from datetime import date
from pathlib import Path

CODE_ROOT = Path(__file__).resolve().parent.parent
KB_CONFIG = CODE_ROOT / "src" / "kb_config.py"
WRAPPER_DIR = Path.home() / ".local" / "bin"

STANDARD_DIRS = ["chroma_db_new", "parent_store", "parent_store_disabled", "data", "outputs", "md"]

WRAPPER_TEMPLATE = """#!/usr/bin/env bash
# {name}-rag — run the shared RAG codebase against the {domain} library ({name}).
# Generated by scripts/setup_library.py on {date}
set -euo pipefail
export BIB_RAG_KB_NAME="${{BIB_RAG_KB_NAME:-{name}}}"
export BIB_RAG_COLLECTION="${{BIB_RAG_COLLECTION:-{collection}}}"
export BIB_RAG_ROOT="${{BIB_RAG_ROOT:-{root}}}"
export PYTHONPATH="${{BIB_RAG_SITE_PACKAGES:-$HOME/.local/lib/python3.10/site-packages}}${{PYTHONPATH:+:$PYTHONPATH}}"

CODEBASE="{code_root}"
SCRIPT="$1"; shift
case "$SCRIPT" in
  /*) ;;
  *)  if [ -f "$CODEBASE/$SCRIPT" ]; then SCRIPT="$CODEBASE/$SCRIPT"
      elif [ -f "$SCRIPT" ]; then SCRIPT="$(cd "$(dirname "$SCRIPT")" && pwd)/$(basename "$SCRIPT")"
      else echo "{name}-rag: script not found: $1" >&2; exit 2; fi ;;
esac
exec /usr/bin/python3.10 -B "$SCRIPT" "$@"
"""

LIBRARY_MD_TEMPLATE = """# LIBRARY.md — {name} ({domain} literature library)

Data-only library consumed by the shared RAG toolkit at {code_root}.
This folder contains NO code — safe to back up, move, or copy as a unit.

## Contents
| Path | What |
|---|---|
| `chroma_db_new/` | ChromaDB, collection `{collection}` (fresh, empty) |
| `parent_store/` | Full-text parent chunks (JSON per paper) |
| `data/` | Per-library checkpoints and metadata logs |
| `outputs/` | Classification tag CSVs, audit reports |
| `CONTEXT.md` | Domain glossary — fill in as vocabulary solidifies |
| `md/` | (optional) extracted markdown source papers |

## Usage
    {name}-rag src/query_bib_rag.py "your query"
    {name}-rag add_papers.py /path/to/pdfs/   # PDF→md→index pipeline

## Status
- Created {today} via scripts/setup_library.py. Empty — no papers indexed yet.
"""

CONTEXT_MD_TEMPLATE = """# CONTEXT.md — {name} ({domain})

Shared vocabulary between you and the agent (borrowed from grill-with-docs).
Terms here are used by writer/grill/agentic tools for this library. Add a term
here BEFORE using it elsewhere; update in the same commit if meaning drifts.

## Domain glossary
(To be populated — add rows as papers are classified.)

| Term | Definition | Use it for |
|------|-----------|-----------|

## Topic taxonomy (for classify_*.py)
Seed topics for classification. Edit freely — the classifier is open-vocab;
these only anchor the prompt.
- (e.g. for geology: stratigraphy, mineralogy, tectonics, geochemistry)
"""


def patch_registry(name: str, root: str, collection: str) -> bool:
    """Insert one entry into _KB_REGISTRY in kb_config.py. Idempotent.
    Uses exact-brace text surgery — regex on '\n}' is dangerous here (it can
    span the whole file and destroy it; that bug shipped once, 2026-08-27).
    """
    s = KB_CONFIG.read_text()
    if f'"{name}":' in s and f'"{root}"' in s:
        print(f"  [--] registry already had '{name}'")
        return False
    # locate the registry dict boundaries by brace counting from its declaration
    marker = "_KB_REGISTRY = {"
    start = s.index(marker) + len(marker) - 1  # position of the opening brace
    depth = 0
    end = None
    for i in range(start, len(s)):
        if s[i] == "{":
            depth += 1
        elif s[i] == "}":
            depth -= 1
            if depth == 0:
                end = i
                break
    if end is None:
        sys.exit(f"ERROR: could not find the closing brace of _KB_REGISTRY in {KB_CONFIG}")
    entry = (f'\n    "{name}": {{\n'
             f'        "root": "{root}",\n'
             f'        "collection": "{collection}",\n'
             f'    }},')
    new = s[:end] + entry + s[end:]
    # sanity: file must still contain the functions after the registry
    for must in ("def get_config", "def parse_kb_arg", "def print_config"):
        if must not in new:
            sys.exit(f"ERROR: patched file lost '{must}' — aborting without write. "
                     f"Fix _KB_REGISTRY manually in {KB_CONFIG}.")
    # atomic write: backup + temp + os.replace (a truncated kb_config.py bricks
    # every tool — this file is the single path-resolution point)
    KB_CONFIG.with_suffix(".py.bak").write_text(s)
    tmp = KB_CONFIG.with_suffix(".py.tmp")
    tmp.write_text(new)
    os.replace(tmp, KB_CONFIG)
    return True


def write_wrapper(name: str, root: str, collection: str, domain: str = "user library") -> Path:
    stem = name[:-4] if name.endswith("_rag") else name
    path = WRAPPER_DIR / f"{stem}-rag"
    path.write_text(WRAPPER_TEMPLATE.format(name=name, root=root,
                                            collection=collection, domain=domain,
                                            code_root=CODE_ROOT, date=date.today()))
    path.chmod(0o755)
    return path


def main():
    ap = argparse.ArgumentParser(description="Scaffold a new RAG library + register it")
    ap.add_argument("--name", help="Library name, e.g. neuro_rag (must end in _rag)")
    ap.add_argument("--root", help="Data root (default: <RAG home>/<name>, where the RAG home defaults to the parent of this repo; override BIB_RAG_HOME)")
    ap.add_argument("--collection", help="Chroma collection name, default <name>_papers")
    ap.add_argument("--domain", help="Short domain description, e.g. 'neuroscience'")
    ap.add_argument("--wrapper", choices=["yes", "no", "ask"], default="ask",
                    help="Emit ~/.local/bin/<name>-rag wrapper")
    ap.add_argument("--no-interactive", action="store_true",
                    help="Fail instead of prompting when a required arg is missing")
    args = ap.parse_args()

    def ask(prompt, default):
        if args.no_interactive:
            return default  # non-interactive mode = accept defaults
        v = input(f"{prompt} [{default}]: ").strip()
        return v or default

    name = args.name or ask("Library name (snake_case, ends in _rag)", "new_rag")
    if not name or not re.fullmatch(r"[a-z][a-z0-9_]*_rag", name):
        sys.exit("ERROR: --name must be lowercase snake_case ending in '_rag' "
                 "(e.g. neuro_rag). This keeps wrappers and registry keys consistent.")
    rag_home = os.environ.get("BIB_RAG_HOME", str(Path(__file__).resolve().parent.parent.parent))
    root = args.root or ask("Data root", str(Path(rag_home) / name))
    collection = args.collection or ask("Collection name", f"{name[:-4]}_papers")
    domain = args.domain or ask("Domain (one line)", "TBD")


    root_path = Path(root)
    print(f"\n=== Scaffolding library '{name}' ===")
    print(f"  root:       {root_path}")
    print(f"  collection: {collection}")
    print(f"  domain:     {domain}")

    # 1. refuse to clobber a populated library (but allow resume of a failed scaffold:
    #    only standard subdirs present + no LIBRARY.md + no chroma.sqlite3 = safe to resume)
    if root_path.exists() and not (root_path / "LIBRARY.md").exists():
        contents = set(os.listdir(root_path)) if root_path.exists() else set()
        has_data = (root_path / "chroma_db_new" / "chroma.sqlite3").exists() or \
                   bool(contents - set(STANDARD_DIRS) - {"md"})
        if has_data:
            if args.no_interactive:
                sys.exit(f"ERROR: {root_path} exists with real data and no LIBRARY.md — "
                         f"refusing to touch it (safety). Use a different --root.")
            ans = input(f"  '{root_path}' exists with data. Continue anyway? [y/N]: ")
            if ans.lower() != "y":
                sys.exit("aborted")
        else:
            print("  [resume] existing empty scaffold detected — continuing")

    # 2. standard subdirs (idempotent)
    for d in STANDARD_DIRS:
        (root_path / d).mkdir(parents=True, exist_ok=True)
    print(f"  [ok] subdirs: {', '.join(STANDARD_DIRS)}")

    # 3. LIBRARY.md + CONTEXT.md (never overwrite existing)
    lib_md = root_path / "LIBRARY.md"
    if not lib_md.exists():
        lib_md.write_text(LIBRARY_MD_TEMPLATE.format(
            name=name, domain=domain, collection=collection, root=root,
            code_root=CODE_ROOT, today=date.today()))
        print(f"  [ok] {lib_md}")
    ctx_md = root_path / "CONTEXT.md"
    if not ctx_md.exists():
        ctx_md.write_text(CONTEXT_MD_TEMPLATE.format(name=name, domain=domain))
        print(f"  [ok] {ctx_md}")

    # 4. registry entry
    if patch_registry(name, str(root_path), collection):
        print(f"  [ok] _KB_REGISTRY patched in {KB_CONFIG}")
        print(f"       >>> commit this change: cd {CODE_ROOT} && git add -A && git commit")
    else:
        print(f"  [--] registry already had '{name}'")

    # 5. wrapper
    do_wrapper = args.wrapper
    if do_wrapper == "ask" and not args.no_interactive:
        do_wrapper = input(f"  Emit wrapper {WRAPPER_DIR}/{name}-rag? [Y/n]: ").strip().lower() or "yes"
    if do_wrapper in ("yes", "y", True):
        w = write_wrapper(name, str(root_path), collection, domain)
        print(f"  [ok] wrapper: {w}")

    # 6. verify resolution
    print("\n=== Verify ===")
    os_env_note = ""
    print(f'  Try: {name[:-4] if name.endswith("_rag") else name}-rag src/query_bib_rag.py "test query"')
    print(f'  Or:  BIB_RAG_KB_NAME={name} <cmd>')
    print("\nNext steps (see GUIDE.md):")
    print(f"  1. Put PDFs somewhere durable, convert to md (pymupdf4llm)")
    print(f"  2. {(name[:-4] if name.endswith('_rag') else name)}-rag src/index_single_paper.py <file.md>   # single paper")
    print(f"     or {(name[:-4] if name.endswith('_rag') else name)}-rag add_papers.py <pdf_dir> for batch")
    print(f"  3. Classify + tag: copy a classify_*.py from scripts/, adapt the topic")
    print(f"     taxonomy for '{domain}', run with {(name[:-4] if name.endswith('_rag') else name)}-rag")
    print(f"  4. Fill in {root_path}/CONTEXT.md with domain vocabulary")
    print(f"  5. Query: {(name[:-4] if name.endswith('_rag') else name)}-rag src/query_bib_rag.py \"...\"")


if __name__ == "__main__":
    main()