"""
Routing logic for the bib_rag agentic graph.

Provides edge routing functions for both the main graph and the agent subgraph.
Adapted from the reference implementation for bib_rag's ChromaDB + llama-server setup.
"""

from typing import Literal
from langgraph.types import Send

from .agent_schemas import State, AgentState
from .agent_nodes import MAX_ITERATIONS, MAX_TOOL_CALLS


def route_after_rewrite(state: State) -> list:
    """Route after query rewriting.

    If the question is unclear, route to request_clarification (the graph
    will interrupt before this node so the user can respond).
    If clear, spawn agent subgraphs for each rewritten query.

    Args:
        state: Current State (main graph)

    Returns:
        Either "request_clarification" or a list of Send() calls for parallel agents.
    """
    if not state.get("questionIsClear", False):
        return "request_clarification"
    else:
        # HyDE passage rides to EVERY subgraph (one passage covers the
        # topic; each sub-question probes it from its own angle).
        hyde = state.get("hydePassage", "") or ""
        return [
            Send(
                "agent",
                {"question": query, "question_index": idx, "messages": [],
                 "hydePassage": hyde},
            )
            for idx, query in enumerate(state["rewrittenQuestions"])
        ]


def route_after_orchestrator_call(state: AgentState) -> Literal["tools", "fallback_response", "collect_answer"]:
    """Route after the orchestrator makes a tool call decision.

    Routing logic:
    - If the last AI message has no tool calls → collect_answer
      (even when the iteration limit was reached: a finished answer must not
      be discarded and re-generated by fallback_response)
    - Else if max iterations or max tool calls reached → fallback_response
    - Otherwise → tools (execute tool calls)

    Args:
        state: Current AgentState

    Returns:
        One of "tools", "fallback_response", or "collect_answer".
    """
    iteration = state.get("iteration_count", 0)
    tool_count = state.get("tool_call_count", 0)

    last_message = state["messages"][-1]
    tool_calls = getattr(last_message, "tool_calls", None) or []

    if not tool_calls:
        return "collect_answer"

    # `tool_count > MAX_TOOL_CALLS` (not `>=`): requests accumulated in the
    # current round may still be executed up to the limit — dropping them
    # would discard planned retrieval without ever running it.
    if iteration >= MAX_ITERATIONS or tool_count > MAX_TOOL_CALLS:
        return "fallback_response"

    return "tools"


def route_after_collect(state: AgentState) -> Literal["orchestrator", "__end__"]:
    """Citation-policy redirect loop (haiku.rag mechanism).

    collect_answer sets guard_redirect=True when the deterministic guard
    stripped every Sources line (nothing citable survived). Instead of
    ending the subgraph with an uncitable answer, route back to the
    orchestrator — collect_answer has already removed the failed answer
    from `messages` and appended the policy feedback, so the retry sees a
    clean conversational state plus the instruction. collect_answer itself
    caps the retries (GUARD_REDIRECT_MAX), so this router only needs to
    check the flag — an exhausted budget arrives here with the flag unset
    and the (annotated) answer in final_answer.
    """
    if state.get("guard_redirect"):
        return "orchestrator"
    return "__end__"
